### ISSUE TITLE
Solução de Erros

### ISSUE THREAD

**Issue by andersonrocha1** [andersonrocha1/projetoJsf2.2PrimeFaces#1]
_**Marcar erros solucionados:**_
- [x] Resolver erro Flyway;

- [x] Resolvendo erro Driver do Postgresql;

`Caused by: java.sql.SQLException: No suitable driver
	at java.sql.DriverManager.getDriver(Unknown Source)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createConnectionFactory(BasicDataSource.java:2151)
	... 54 more`;

**Comment by andersonrocha1** [comment]
Troquei o drive do postgresql e comentei esta linha : . Depois notei em um erro a falta da tabela revinfo, que havia removido para outro teste e acabei esquecendo de recriá-la. Quando recriei, o script de sql da pasta db.migration entrou em operação pelo flyway.  Conclusão do erro:
* Não era somente o drive...
